name: Github Actions Test

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job: # job을 식별하기 위한 ID
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    steps:
      - name: test 해보기 # STEP마다 이름을 붙일 수 있음
        run: echo "test~"

      - name: test 2
        run: | 
          echo "test2"
          echo "testing"
          echo "How to use it"

      - name: test 3 - Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: test 4 - Github Actions 비밀 값 test
        run: |
          echo ${{secrets.MY_NAME}}
        
